### ISSUE TITLE
hello?

### ISSUE THREAD

**Issue by i-stole-your-shoelaces** [kfischer-okarin/lfs-vxace#1]
hi, um,, i was just wondering, how exactly do i use this script?

do i just paste everything into the scripts bit? the read me file isn't very clear on how exactly to set everything up.

im sorry, i don't understand it very well...

so um, could you please clarify how to use this script please?? 

thank you! （＞人＜；）

**Comment by kfischer-okarin** [comment]
Hi,

the script you are looking for is here:

https://raw.githubusercontent.com/kfischer-okarin/VXAceScripts/master/Language%20File%20System%20-%20Core.rb

Read the documentation in the header for further instructions.....

**Comment by i-stole-your-shoelaces** [comment]
thanks!
